"""Initial migration

Revision ID: 3180485498e0
Revises: 
Create Date: 2026-08-22 22:04:04.642132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3180485498e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_aplicacao_id'), 'aplicacao', ['id'], unique=False)
    op.alter_column('areas', 'nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('areas', 'sigla',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.drop_index(op.f('idx_ativo_nome'), table_name='ativo')
    op.drop_index(op.f('idx_ativo_tipo'), table_name='ativo')
    op.create_index(op.f('ix_ativo_id'), 'ativo', ['id'], unique=False)
    op.create_index(op.f('ix_ativo_nome'), 'ativo', ['nome'], unique=False)
    op.drop_index(op.f('idx_audit_entidade'), table_name='audit_log')
    op.create_index(op.f('ix_audit_log_entidade'), 'audit_log', ['entidade'], unique=False)
    op.create_unique_constraint(None, 'namespace', ['nome'])
    op.drop_index(op.f('idx_rel_destino'), table_name='relacionamento')
    op.drop_index(op.f('idx_rel_origem'), table_name='relacionamento')
    op.drop_index(op.f('idx_rel_tipo'), table_name='relacionamento')
    op.drop_index(op.f('ix_service_accounts_token'), table_name='service_accounts')
    op.create_unique_constraint(None, 'service_accounts', ['token'])
    op.drop_column('servico', 'created_at')
    op.alter_column('sor', 'abreviacao',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('sor', 'lifecycle',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint(op.f('sor_unique_1'), 'sor', type_='unique')
    op.drop_column('tipo_ativo', 'descricao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_ativo', sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('sor_unique_1'), 'sor', ['descricao'], postgresql_nulls_not_distinct=False)
    op.alter_column('sor', 'lifecycle',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('sor', 'abreviacao',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('servico', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'service_accounts', type_='unique')
    op.create_index(op.f('ix_service_accounts_token'), 'service_accounts', ['token'], unique=True)
    op.create_index(op.f('idx_rel_tipo'), 'relacionamento', ['tipo_id'], unique=False)
    op.create_index(op.f('idx_rel_origem'), 'relacionamento', ['origem_id'], unique=False)
    op.create_index(op.f('idx_rel_destino'), 'relacionamento', ['destino_id'], unique=False)
    op.drop_constraint(None, 'namespace', type_='unique')
    op.drop_index(op.f('ix_audit_log_entidade'), table_name='audit_log')
    op.create_index(op.f('idx_audit_entidade'), 'audit_log', ['entidade'], unique=False)
    op.drop_index(op.f('ix_ativo_nome'), table_name='ativo')
    op.drop_index(op.f('ix_ativo_id'), table_name='ativo')
    op.create_index(op.f('idx_ativo_tipo'), 'ativo', ['tipo_id'], unique=False)
    op.create_index(op.f('idx_ativo_nome'), 'ativo', ['nome'], unique=False)
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.alter_column('areas', 'sigla',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('areas', 'nome',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_aplicacao_id'), table_name='aplicacao')
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('totp_secret', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('totp_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuario_pkey')),
    sa.UniqueConstraint('username', name=op.f('usuario_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('api_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('api_token_pkey')),
    sa.UniqueConstraint('token', name=op.f('api_token_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('usuario_backup_code',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('usado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('usuario_backup_code_usuario_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('usuario_backup_code_pkey'))
    )
    # ### end Alembic commands ###
