"""Add token_hash column to service_accounts

Revision ID: 45529f9a81e0
Revises: 3180485498e0
Create Date: 2026-08-23 21:38:39.926772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45529f9a81e0'
down_revision: Union[str, Sequence[str], None] = '3180485498e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_backup_code')
    op.drop_table('api_token')
    op.drop_table('usuario')
    op.alter_column('audit_log', 'antes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_log', 'depois',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_entidade_created_at', 'audit_log', ['entidade', 'created_at'], unique=False)
    op.create_index('ix_audit_log_entidade_entidade_id', 'audit_log', ['entidade', 'entidade_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entidade_id'), 'audit_log', ['entidade_id'], unique=False)
    op.alter_column('endereco_ip', 'ip',
               existing_type=postgresql.INET(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index('ix_endereco_ip_ativo_id_ip', 'endereco_ip', ['ativo_id', 'ip'], unique=True)
    op.create_index(op.f('ix_instancia_aplicacao_aplicacao_id'), 'instancia_aplicacao', ['aplicacao_id'], unique=False)
    op.create_index(op.f('ix_relacionamento_destino_id'), 'relacionamento', ['destino_id'], unique=False)
    op.create_index(op.f('ix_relacionamento_origem_id'), 'relacionamento', ['origem_id'], unique=False)
    op.add_column('service_accounts', sa.Column('token_hash', sa.String(length=255), nullable=True))
    # Update existing rows with a default value
    op.execute("UPDATE service_accounts SET token_hash = 'legacy_token' WHERE token_hash IS NULL")
    op.alter_column('service_accounts', 'token_hash', nullable=False)
    op.drop_constraint(op.f('service_accounts_token_key'), 'service_accounts', type_='unique')
    op.create_unique_constraint(None, 'service_accounts', ['token_hash'])
    op.drop_column('service_accounts', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_accounts', sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service_accounts', type_='unique')
    op.create_unique_constraint(op.f('service_accounts_token_key'), 'service_accounts', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('service_accounts', 'token_hash')
    op.drop_index(op.f('ix_relacionamento_origem_id'), table_name='relacionamento')
    op.drop_index(op.f('ix_relacionamento_destino_id'), table_name='relacionamento')
    op.drop_index(op.f('ix_instancia_aplicacao_aplicacao_id'), table_name='instancia_aplicacao')
    op.drop_index('ix_endereco_ip_ativo_id_ip', table_name='endereco_ip')
    op.alter_column('endereco_ip', 'ip',
               existing_type=sa.String(),
               type_=postgresql.INET(),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_log_entidade_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_entidade_entidade_id', table_name='audit_log')
    op.drop_index('ix_audit_log_entidade_created_at', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.alter_column('audit_log', 'depois',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_log', 'antes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('totp_secret', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('totp_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuario_pkey')),
    sa.UniqueConstraint('username', name=op.f('usuario_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('api_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('api_token_pkey')),
    sa.UniqueConstraint('token', name=op.f('api_token_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('usuario_backup_code',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('usado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('usuario_backup_code_usuario_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('usuario_backup_code_pkey'))
    )
    # ### end Alembic commands ###
