"""baseline schema completo

Revision ID: 68bb57b2a384
Revises: 
Create Date: 2026-09-18 10:21:37.214112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent.parent / "backend"))

from models import EncryptedText

# revision identifiers, used by Alembic.
revision: str = '68bb57b2a384'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambiente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('aplicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sistema', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('linguagens', sa.String(length=255), nullable=True),
    sa.Column('bancos_dados', sa.String(length=255), nullable=True),
    sa.Column('area_tecnologia', sa.String(length=255), nullable=True),
    sa.Column('area_negocio', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sistema')
    )
    op.create_index(op.f('ix_aplicacao_id'), 'aplicacao', ['id'], unique=False)
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('sigla')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidade', sa.String(length=100), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=True),
    sa.Column('antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('depois', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usuario', EncryptedText(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entidade'), 'audit_log', ['entidade'], unique=False)
    op.create_index('ix_audit_log_entidade_created_at', 'audit_log', ['entidade', 'created_at'], unique=False)
    op.create_index('ix_audit_log_entidade_entidade_id', 'audit_log', ['entidade', 'entidade_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entidade_id'), 'audit_log', ['entidade_id'], unique=False)
    op.create_table('criticidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nivel')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('arquivo', sa.String(length=512), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('conteudo_hash', sa.String(length=64), nullable=False),
    sa.Column('indexado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documento_nome'), 'documento', ['nome'], unique=True)
    op.create_table('service_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('totp_secret', EncryptedText(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_service_accounts_id'), 'service_accounts', ['id'], unique=False)
    op.create_table('sor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abreviacao', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('lifecycle', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abreviacao')
    )
    op.create_table('status_ativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipo_ativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipo_relacionamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('ativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('ambiente_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('criticidade_id', sa.Integer(), nullable=True),
    sa.Column('sor_id', sa.Integer(), nullable=True),
    sa.Column('areas_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambiente.id'], ),
    sa.ForeignKeyConstraint(['areas_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['criticidade_id'], ['criticidade.id'], ),
    sa.ForeignKeyConstraint(['sor_id'], ['sor.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status_ativo.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_ativo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ativo_id'), 'ativo', ['id'], unique=False)
    op.create_index(op.f('ix_ativo_nome'), 'ativo', ['nome'], unique=False)
    op.create_table('trecho_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('titulo_secao', sa.String(length=255), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trecho_documento_documento_id'), 'trecho_documento', ['documento_id'], unique=False)
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ativo_id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('endereco_ip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('primario', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endereco_ip_ativo_id'), 'endereco_ip', ['ativo_id'], unique=False)
    op.create_index('ix_endereco_ip_ativo_id_ip', 'endereco_ip', ['ativo_id', 'ip'], unique=True)
    op.create_index(op.f('ix_endereco_ip_id'), 'endereco_ip', ['id'], unique=False)
    op.create_index(op.f('ix_endereco_ip_ip'), 'endereco_ip', ['ip'], unique=False)
    op.create_table('instancia_aplicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aplicacao_id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=True),
    sa.Column('porta', sa.Integer(), nullable=True),
    sa.Column('path_execucao', sa.String(length=255), nullable=True),
    sa.Column('comando_execucao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['aplicacao_id'], ['aplicacao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ativo_id')
    )
    op.create_index(op.f('ix_instancia_aplicacao_aplicacao_id'), 'instancia_aplicacao', ['aplicacao_id'], unique=False)
    op.create_table('relacionamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['destino_id'], ['ativo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origem_id'], ['ativo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_relacionamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relacionamento_destino_id'), 'relacionamento', ['destino_id'], unique=False)
    op.create_index(op.f('ix_relacionamento_origem_id'), 'relacionamento', ['origem_id'], unique=False)
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('ativo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ativo_id')
    )
    op.create_table('servico_negocio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ativo_id')
    )
    op.create_table('namespace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('ativo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ativo_id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('namespace')
    op.drop_table('servico_negocio')
    op.drop_table('servico')
    op.drop_index(op.f('ix_relacionamento_origem_id'), table_name='relacionamento')
    op.drop_index(op.f('ix_relacionamento_destino_id'), table_name='relacionamento')
    op.drop_table('relacionamento')
    op.drop_index(op.f('ix_instancia_aplicacao_aplicacao_id'), table_name='instancia_aplicacao')
    op.drop_table('instancia_aplicacao')
    op.drop_index(op.f('ix_endereco_ip_ip'), table_name='endereco_ip')
    op.drop_index(op.f('ix_endereco_ip_id'), table_name='endereco_ip')
    op.drop_index('ix_endereco_ip_ativo_id_ip', table_name='endereco_ip')
    op.drop_index(op.f('ix_endereco_ip_ativo_id'), table_name='endereco_ip')
    op.drop_table('endereco_ip')
    op.drop_table('cluster')
    op.drop_index(op.f('ix_trecho_documento_documento_id'), table_name='trecho_documento')
    op.drop_table('trecho_documento')
    op.drop_index(op.f('ix_ativo_nome'), table_name='ativo')
    op.drop_index(op.f('ix_ativo_id'), table_name='ativo')
    op.drop_table('ativo')
    op.drop_table('tipo_relacionamento')
    op.drop_table('tipo_ativo')
    op.drop_table('status_ativo')
    op.drop_table('sor')
    op.drop_index(op.f('ix_service_accounts_id'), table_name='service_accounts')
    op.drop_table('service_accounts')
    op.drop_index(op.f('ix_documento_nome'), table_name='documento')
    op.drop_table('documento')
    op.drop_table('criticidade')
    op.drop_index(op.f('ix_audit_log_entidade_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_entidade_entidade_id', table_name='audit_log')
    op.drop_index('ix_audit_log_entidade_created_at', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entidade'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_aplicacao_id'), table_name='aplicacao')
    op.drop_table('aplicacao')
    op.drop_table('ambiente')
    # ### end Alembic commands ###
